name: Hello World Workflow!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo 'Hello World!'
      - name: Step 2
        run: |
          echo 'Hello World again!'
